name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Or your preferred Node.js version

      - name: Inject Firebase Config
        run: |
          echo "export const FIREBASE_CONFIG = {
              apiKey: \"${{ secrets.FIREBASE_API_KEY }}\",
              authDomain: \"integracaocoi.firebaseapp.com\",
              projectId: \"integracaocoi\",
              storageBucket: \"integracaocoi.firebasestorage.app\",
              messagingSenderId: \"177203745489\",
              appId: \"1:177203745489:web:b86bbc4e96830e06032bf0\"
          };

          export const APP_ID_FALLBACK = 'integracaocoi';" > firebase_config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Adjust if your build output is in a subdirectory
          
